-- Sample Data for VetCare Clinic

-- 1. Doctors
INSERT INTO `doctors` (`DoctorID`, `Name`, `Email`, `Password`, `IsActive`) VALUES
(1, 'Dr. Smith', 'dr.smith@vetcare.com', '$2y$10$yourhashedpassword', 1),
(2, 'Dr. Jones', 'dr.jones@vetcare.com', '$2y$10$anotherhashedpass', 1);

-- 2. Master Medicines
INSERT INTO `medicines` (`Mid`, `name`, `type`, `description`, `UnitPrice`, `taxExcluded_price`, `taxAmount`, `hsn`, `taxable`, `Itax`, `cess`, `submittedby`, `status`) VALUES
(1, 'Amoxicillin', 'Tablet', 'Antibiotic', '10', '9', '1', '3004', 'yes', '12', '0', 'admin', 'available'),
(2, 'Carprofen', 'Tablet', 'Pain Relief', '25', '22', '3', '3004', 'yes', '12', '0', 'admin', 'available'),
(3, 'Ivermectin', 'Injection', 'Anti-parasitic', '150', '140', '10', '3004', 'yes', '12', '0', 'admin', 'available'),
(4, 'Fipronil', 'Drops', 'Flea and Tick', '200', '180', '20', '3808', 'yes', '12', '0', 'admin', 'available');

-- 3. Master Vaccinations
INSERT INTO `vaccination` (`VId`, `name`, `amount`, `type`, `duration`, `submittedBy`) VALUES
(1, 'Rabies Vaccine', '500', 'IM', '1 Year', 'admin'),
(2, 'Distemper Combo (DHPP)', '750', 'SC', '1 Year', 'admin'),
(3, 'Feline Combo (FVRCP)', '700', 'SC', '1 Year', 'admin');

-- 4. Master Laboratory Tests
INSERT INTO `laboratory` (`Lid`, `name`, `amount`, `submittedBy`) VALUES
(1, 'Complete Blood Count (CBC)', '600', 'admin'),
(2, 'Urinalysis', '400', 'admin'),
(3, 'Fecal Exam', '350', 'admin'),
(4, 'X-Ray - Single View', '1200', 'admin');

-- 5. Sample Patient Registrations
-- Note: RegNo format is YYYY-ID. This should ideally be generated by the application logic.
INSERT INTO `registration` (`RegID`, `RegDt`, `RegNo`, `Pettyp`, `petnam`, `petsex`, `petbred`, `year`, `month`, `gram`, `kg`, `petsp`, `ownnam`, `ownmob`, `ownemail`, `dt`) VALUES
(1, '2023-10-01', '2023-10001', 'Dog', 'Buddy', 'Male', 'Golden Retriever', '3', '5', '0', '28', 'Canine', 'John Doe', '9876543210', 'john.doe@email.com', '2023-10-01'),
(2, '2023-10-02', '2023-10002', 'Cat', 'Whiskers', 'Female', 'Siamese', '2', '1', '0', '4', 'Feline', 'Jane Smith', '8765432109', 'jane.smith@email.com', '2023-10-02'),
(3, '2023-10-03', '2023-10003', 'Dog', 'Lucy', 'Female', 'Beagle', '5', '0', '0', '12', 'Canine', 'Peter Pan', '7654321098', 'peter.pan@email.com', '2023-10-03');

-- 6. Sample Consultation Bookings for Today
-- Assuming today's date is the date you are running this script.
-- The DoctorID = 1 corresponds to Dr. Smith.
INSERT INTO `consultation_booking` (`RegID`, `DoctorID`, `BookingDate`, `Status`) VALUES
(1, 1, CURDATE(), 'not checked'),
(2, 1, CURDATE(), 'not checked'),
(3, 1, CURDATE(), 'checked'); -- One patient already checked to show the status difference.

-- To show a full history for one patient, let's add a past consultation for Buddy (RegID 1)
-- First, a past booking
INSERT INTO `consultation_booking` (`RegID`, `DoctorID`, `BookingDate`, `Status`) VALUES
(1, 1, '2023-04-15', 'checked');

-- Then, the past consultation data itself
-- (This requires getting the BookingID from the previous insert, let's assume it's 4 for this example)
INSERT INTO `consultations` (`BookingID`, `RegID`, `Temperature`, `Weight`, `DiagnosisNotes`, `ConsultationDate`) VALUES
(4, 1, '101.5 F', 27.5, 'Annual checkup. Mild tartar on teeth. Advised dental cleaning.', '2023-04-15 11:30:00');

-- And a vaccine given during that past consultation
-- (This requires getting the ConsultationID from the previous insert, let's assume it's 1 for this example)
INSERT INTO `consultation_injections` (`ConsultationID`, `VaccinationID`, `InjectionName`, `Dosage`) VALUES
(1, 1, 'Rabies Vaccine', '1ml');
